version: "3.8"
services:
  postgresDB:
    image: postgres:16.1
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_crud
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"